### ISSUE TITLE
cannot execute binary file

### ISSUE THREAD

**Issue by angelinetran** [amv/serverless-screenshot-get#2]
Hi there! 

I followed the steps you outlined in your README file, including the section titled "Add binary data support to API Gateway," but I still get the following error when I try to reach my endpoint. Could you help me figure out the error below?

Thanks!

```
Error: Command failed: /var/task/phantomjs/phantomjs-2.1.1-linux-x86_64 --ignore-ssl-errors=true /var/task/phantomscript.js {"preloadurl":"","preloadevalcode":"","preloadevaldelay":"10","preloaddelay":"100","url":"https://google.com/","file":"/tmp/1506957763752.png","width":"1280","height":"1024","clip":"","clipheight":0,"clipwidth":0,"cliptop":0,"clipleft":0,"clipwithiframe":"","iframescrollto":0,"iframescrolldelay":"50","evalcode":"","evaldelay":10,"delay":"100","timeout":"29000"}
/var/task/phantomjs/phantomjs-2.1.1-linux-x86_64: /var/task/phantomjs/phantomjs-2.1.1-linux-x86_64: cannot execute binary file


STDOUT:
```

**Comment by amv** [comment]
Hi!

Would it be possible for you to see if the suggestions here would help with your issue?

https://github.com/graphcool/chromeless/issues/273

I think namely it might be just installing a different version of serverless:

`npm install -g serverless@1.21.1`

**Comment by angelinetran** [comment]
That was it! 💯  Thanks so much.
